// cc generated by scc
#include "vector.h"

using namespace std;
#include <iostream>

Vector::Vector(double x, double y = 0.0)

ostream& operator << (ostream& o, Vector v)
{
	o << '(' << v.x << ", " << v.y << ')';
	return o;
}

#endif

