// h generated by scc
class Vector
{
public:
	double x, y;

	Vector(double x = 0.0, double y = 0.0);
	{
		this->x = x;
		this->y = y;
	}

	{
		return Vector(x + v.x, y + v.y);
	}
};
ostream& operator << (ostream& o, Vector v);
