#!/bin/bash

CC=gcc
DEBUG=" -g -D__DEBUG__"
CFLAGS=" $DEBUG -std=c99"

for file in ./src/*.c; do
	outfile="`echo $file|sed 's/.*\/\(.*\)\.c/\.\/build\/\1/g'`"

	if [ "$file" -ot "$outfile" ]; then
		echo -e "\033[01;33mSkip\033[0m $file"
		continue
	fi

	echo -e "\033[01;32mCompiling\033[0m $file"
	cmd="$CC $CFLAGS -o $outfile $file"
	echo -e "\033[00;36m$cmd"
	echo -e "\033[01;31m" # If there's any output, it will show in RED
	if ! $cmd; then echo -e "\033[0m"; exit $?; fi
	echo -e "\033[0m"
done
# Debug
./debug
