#!/bin/bash

echo -e "\033[01;34m============ DEBUG ============\033[0m"

if [ "$1" != "" ]; then
	files=""
	while [ "$1" != "" ]; do
		files="$files ./build/ex$1"
		shift
	done
else
	files="./build/*"
fi

for file in $files; do
	echo -en "\033[01;32mFile `echo $file|sed 's/.*\/\(.*\)$/\1/g'`"
	echo -en "\033[0m (Press RETURN to execute...)"
	read cmd
	if [ "$cmd" == "q" ]; then break; fi;
	if [ "$cmd" == "s" ]; then continue; fi;
	$file
done
