#!/usr/bin/awk -f

# BEGIN{tt=0;}{if($0 !=""){if(!($0 in cmds))cmds[$0]=1;else cmds[$0]++;tt++;}}END{for(cmd in cmds)print cmds[cmd]"\t"cmd;print"Total:"tt;}

BEGIN {
	tt=0;
}

{
	if ($0 != ""){
		if (!($0 in cmds)) 
			cmds[$0] = 1;
		else 
			cmds[$0]++;
		tt++;
	}
}

END {
	for (cmd in cmds)
		print cmds[cmd] "\t" cmd;
	print "Total: " tt;
}

